name: deploy cloud function
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: 'actions/checkout@v4'
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/639051812907/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-cloud-function-deployer@circular-ether-368213.iam.gserviceaccount.com'
    
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v3'
      timeout-minutes: 10
      with:
        name: 'resource-planning-loader'
        region: 'europe-west3'
        source_dir: './src/'
        runtime: 'python312'
        entry_point: 'main'
        memory: '512M'
        max_instance_count: 1
        max_instance_request_concurrency: 1
        ingress_settings: 'ALLOW_ALL'
        service_account: 'sheets-bigquery-sa@circular-ether-368213.iam.gserviceaccount.com'
        service_timeout: '1500s'
        event_trigger_type: 'google.cloud.pubsub.topic.v1.messagePublished'
        event_trigger_pubsub_topic: 'projects/circular-ether-368213/topics/resource-planning-loader'
        event_trigger_retry: true