name: deploy resource planning function
on: 
  push:
    branches:
      - main
    paths:
      - 'cloud_functions/resource_planning/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: 'actions/checkout@v4'
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'circular-ether-368213'
        credentials_json: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}
    
    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v3'
      timeout-minutes: 10
      with:
        name: 'resource-planning-loader'
        region: 'europe-west3'
        source_dir: './cloud_functions/resource_planning/'
        runtime: 'python312'
        entry_point: 'main'
        cpu: 0.167
        memory: '512M'
        timeout: 540
        min_instances: 0
        max_instances: 1
        event_trigger_type: 'cloud.pubsub.topic.v1.messagePublished'
        event_trigger_pubsub_topic: 'projects/circular-ether-368213/topics/resource-planning-loader'
        event_trigger_retry: false